---
# Preparation stage

- name: Install necessary libs and packages
  become: yes
  apt: 
    pkg: "{{ item }}"
    state: installed 
    update_cache: true
  with_items:
    - build-essential
    - gcc-multilib
    - libxext-dev
    - libxpm-dev
    - x11proto-xext-dev
  
- name: Install Mercurial
  become: yes
  apt: pkg=mercurial state=installed update_cache=true
